# Generated by Django 5.1.5 on 2025-04-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='inCart',
            field=models.BooleanField(default=False),
        ),
    ]
