# Generated by Django 5.1.5 on 2025-04-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pokemonCard_images/')),
            ],
        ),
    ]
