# Generated by Django 5.1.5 on 2025-04-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonCard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncard',
            name='image',
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/120'),
        ),
    ]
