# Generated by Django 5.1.5 on 2025-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonCard', '0002_remove_pokemoncard_image_pokemoncard_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='defense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='type',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
